// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreatePayment(ctx context.Context, bookingid int64) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBooking(ctx context.Context, bookingid int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetBooking(ctx context.Context, bookingid int64) (Booking, error)
	GetBookingPayment(ctx context.Context, bookingid int64) (Payment, error)
	GetBookings(ctx context.Context, arg GetBookingsParams) ([]Booking, error)
	GetBookingsFromToday(ctx context.Context, bookstarts time.Time) ([]Booking, error)
	GetPayments(ctx context.Context, arg GetPaymentsParams) ([]Payment, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserBookings(ctx context.Context, arg GetUserBookingsParams) ([]Booking, error)
	GetUserLogin(ctx context.Context, mobileNumber string) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
