// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name,
    email,
    mobile_number,
    password,
    user_type
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, full_name, email, mobile_number, password, created_at, user_type
`

type CreateUserParams struct {
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	MobileNumber string `json:"mobile_number"`
	Password     string `json:"password"`
	UserType     Usert  `json:"user_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.MobileNumber,
		arg.Password,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.MobileNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UserType,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, mobile_number, password, created_at, user_type FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.MobileNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UserType,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, full_name, email, mobile_number, password, created_at, user_type FROM users
ORDER BY full_name
LIMIT $1
OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.MobileNumber,
			&i.Password,
			&i.CreatedAt,
			&i.UserType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
    set full_name = $2,
    email = $3,
    mobile_number = $4,
    password = $5
WHERE id = $1
RETURNING id, full_name, email, mobile_number, password, created_at, user_type
`

type UpdateUserParams struct {
	ID           int64  `json:"id"`
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	MobileNumber string `json:"mobile_number"`
	Password     string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.MobileNumber,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.MobileNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UserType,
	)
	return i, err
}
